source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Mega' do
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.1'
pod 'Kingfisher', '~> 4.8'
pod 'Cosmos', '~> 16.0'
end
